name: yarucinnamon
version: 0.0.0-dev.5

description: Ubuntu Yaru Cinnamon theme

homepage: https://github.com/Ubuntu-Cinnamon-Remix/yarucinnamon.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/yarucinnamon/fonts/Ubuntu-L.ttf
          weight: 300
        - asset: packages/yarucinnamon/fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/yarucinnamon/fonts/Ubuntu-R.ttf
          weight: 400
        - asset: packages/yarucinnamon/fonts/Ubuntu-RI.ttf
          weight: 400
          style: italic
        - asset: packages/yarucinnamon/fonts/Ubuntu-M.ttf
          weight: 500
        - asset: packages/yarucinnamon/fonts/Ubuntu-MI.ttf
          weight: 500
          style: italic
        - asset: packages/yarucinnamon/fonts/Ubuntu-B.ttf
          weight: 700
        - asset: packages/yarucinnamon/fonts/Ubuntu-BI.ttf
          weight: 700
          style: italic
    - family: Noto Sans CJK
      fonts:
        - asset: packages/yarucinnamon/fonts/NotoSansCJK-Regular.ttc
          weight: 300
        - asset: packages/yarucinnamon/fonts/NotoSansCJK-Bold.ttc
          weight: 700
    - family: Tibetan Machine Uni
      fonts:
        - asset: packages/yarucinnamon/fonts/TibetanMachineUni.ttf
          weight: 300
    - family: Liberation Serif
      fonts:
        - asset: packages/yarucinnamon/fonts/LiberationSerif-Regular.ttf
          weight: 300
        - asset: packages/yarucinnamon/fonts/LiberationSerif-Italic.ttf
          weight: 300
          style: italic
        - asset: packages/yarucinnamon/fonts/LiberationSerif-Bold.ttf
          weight: 700
        - asset: packages/yarucinnamon/fonts/LiberationSerif-BoldItalic.ttf
          weight: 700
          style: italic
